import java.util.Random;
import java.util.Scanner;

public class DogGenetics {

    public static void main(String[] args) {

        // takes input for a dog name.
        Scanner dogInput = new Scanner(System.in);
        System.out.println("What is your dog's name? ");
        String dogName = dogInput.next();

        // Array of dog names which will each be assigned a random percentage.
        String[] dogBreeds = {"German Shepperd","Chihuahua","Labrador","Jack Russel","Bull-dog"};
        Random random = new Random(); // will be used to generate a random number.

        //Generating 5 random numbers that add up to 100 using a simple formula.
        //First 4 numbers have a max bound that follows from the previous number
        // e.g. 1st is 100 2nd is (100-number1=43 ->bound:57...etc)
        int number1 = random.nextInt(100);
        int number2 = random.nextInt(100-number1);
        int number3 = random.nextInt(100-number1-number2);
        int number4 = random.nextInt(100-number1-number2-number3);
        //this number is generated by just subtracting all the other 4 random numbers from 100 to ensure it is in the total sum of 100.
        int number5 = 100 - number1 - number2 - number3 - number4;
        // for printing it in one loop
        int[] percentages = {number1,number2,number3,number4,number5};

        //printing everything.
        System.out.println("Well then, I have this highly reliable report on " + dogName+ "'s prestigious background right here.\n");
        System.out.println(dogName+" is:\n");
        for (int i = 0; i < dogBreeds.length; i++) {
            System.out.println(percentages[i]+ "% " + dogBreeds[i]);
        }//end for loop

        System.out.println("\nWow, that's QUITE the dog!");
        }//end main

    }//end class

